SOURCES=testZIV.c testSIV.c testMIV.c
TEXT_TARGETS=$(SOURCES:.c=.ll)
BIN_TARGETS=$(SOURCES:.c=.bc)

all: $(BIN_TARGETS) $(TEXT_TARGETS)
	@echo OK
%.ll: %.bc
	llvm-dis $^
%.bc: %.c
	clang -O0 -emit-llvm -c -o $@ $^
